---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required ".values.name must be specified" .Values.name }}-registry-deployment
  labels:
    app: {{ .Values.name }}-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-registry
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-registry
    spec:
      containers:
        - name: {{ .Values.name }}-registry
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          env:
            {{- range .Values.verifiers }}
            - name: VERIFIERS__{{ .type }}
              value: http://{{ .name }}-verifier:80
            {{- end }}
            - name: VERIFIABLEEVENTSTORE__BATCHSIZEEXPONENT
              value: {{ .Values.verifiableEventStore.batchSizeExponent | quote }}
            - name: VERIFIABLEEVENTSTORE__EVENTSTORE__TYPE
              value: {{ .Values.verifiableEventStore.eventStore.type }}
            - name: IMMUTABLELOG__TYPE
              value: {{ .Values.immutableRecord.type }}
            {{- if eq .Values.immutableRecord.type "concordium" }}
            - name: IMMUTABLELOG__CONCORDIUM__ADDRESS
              value: {{ .Values.immutableRecord.concordium.rpcUrl }}
            - name: IMMUTABLELOG__CONCORDIUM__AUTHENTICATIONTOKEN
              value: {{ .Values.immutableRecord.concordium.rpcToken }}
            - name: IMMUTABLELOG__CONCORDIUM__ACCOUNTADDRESS
              value: {{ required "When type is concordium, accountAddress must be set" .Values.immutableRecord.concordium.accountAddress }}
            - name: IMMUTABLELOG__CONCORDIUM__ACCOUNTKEY
              valueFrom:
                secretKeyRef:
                  name: {{ required "When type is concordium, accountKeySecret.name must be set" .Values.immutableRecord.concordium.accountKeySecret.name }}
                  key: {{ required "When type is concordium, accountKeySecret.key must be set" .Values.immutableRecord.concordium.accountKeySecret.key }}
            {{- end }}
