apiVersion: v1
kind: Service
metadata:
  name: project-origin
spec:
  type: ClusterIP
  selector:
    app: po-registry
  ports:
    - name: grpc
      protocol: TCP
      port: 80
      targetPort: 80
