{{- define "common.database.config" -}}
# Database Configuration
- name: DB_HOST
  {{- include "common.setValue" (list .Values.postgresql.host ".postgresql.host") | nindent 2 }}
- name: DB_PORT
  {{- include "common.setValue" (list .Values.postgresql.port ".postgresql.port") | nindent 2 }}
- name: DB_DATABASE
  {{- include "common.setValue" (list .Values.postgresql.database ".postgresql.database") | nindent 2 }}
- name: DB_USERNAME
  {{- include "common.setValue" (list .Values.postgresql.username ".postgresql.username") | nindent 2 }}
- name: DB_PASSWORD
  {{- include "common.setValue" (list .Values.postgresql.password ".postgresql.password") | nindent 2 }}
- name: ConnectionStrings__Database
  value: Host=$(DB_HOST); Port=$(DB_PORT); Database=$(DB_DATABASE); Username=$(DB_USERNAME); Password=$(DB_PASSWORD);
{{- end }}

