{{- define "common.otlp.config" -}}
- name: Otlp__Enabled
  value: {{ .enabled | quote }}
{{- if .enabled }}
- name: Otlp__Endpoint
  value: {{ required "otel.endpoint is required when enabled" .endpoint | quote }}
{{- end }}
{{- end -}}
