name: "📝 Architecture Decision Record"
description: "Create an Architecture Decision Record to document a decision that has been made (or is under discussion) regarding a larger feature or aspect related to developing the registry"
title: "📝 [ADR] - <title>"
labels: [
  "documentation"
]
body:
  - type: textarea
    id: context
    attributes:
      label: "Context"
      description: Provide some context for the ADR, such as the problem or issue that it addresses.  
      placeholder: "Describe the context in a few lines"
    validations:
      required: true
  - type: textarea
    id: decision
    attributes:
      label: "Decision"
      description: Describe the decision that was made and the rationale behind it.
      placeholder: "In a few lines here"
      render: bash
    validations:
      required: true
  - type: textarea
    id: consequences
    attributes:
      label: "Consequences"
      description: Outline the consequences of the decision, both positive and negative.  
      placeholder: "Describe the consequences here"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: (List and) Describe any alternative solutions that were considered, and why they were not chosen.
      placeholder: "Add any alternatives considered here"
    validations:
      required: false
  - type: textarea
    id: related
    attributes:
      label: "Related Material"
      description: Provide links to any related documents or resources, such as RFCs, discussions or code.
       placeholder: "Add any related links here"
    validations:
      required: false
  - type: dropdown
    id: status
    attributes:
      label: "Status"
      description: Indicate the current status of the ADR. such as "proposed," "accepted," or "rejected".
      multiple: false
      options:
        - Proposed
        - Accepted
        - Rejected
    validations:
      required: true
