name: "🐞 Bug Report"
description: "Create a report to help us improve"
title: "🐞 [BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the Bug"
      description: A clear and concise description of what the bug is.  
      placeholder: "Describe the bug in a few lines"
    validations:
      required: true
  - type: textarea
    id: reproduce_info
    attributes:
      label: "To Reproduce"
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: A clear and concise description of what you expect to happen.      
      placeholder: "Describe the expected behavior in a few lines"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      placeholder: "Add a few screenshots here, illustrating the problem"
    validations:
      required: false
  - type: textarea
    id: desktop
    attributes:
      label: "Desktop"
      description: Please complete the following information. If this bug does not involve access through a browser (because it is e.g. a API issue, server bug, smartphone, etc.) please state the context information you have from there as much as it exists or state "not applicable" if there is none.
      value: |
        - OS: [e.g. iOS]
        - Version [e.g. 22]
        - Browser [e.g. chrome, safari]        
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: Add any other context about the problem here.
      placeholder: "A few lines describing additional context, such as related #Issue ID or #Pull Request ID"
    validations:
      required: false
