# global values
global:
  # imageRegistry is the global docker image registry that will override the image registry for all images in all charts
  imageRegistry: ""

# image holds the configuration for the image to use for the registry
image:
  registry: ghcr.io
  # repository is the repository to pull the image from
  repository: project-origin/registry-server
  # tag is the tag to pull defaults to the chart version
  tag:

# resources holds the configuration for the resource requests and limits
resources:
  # requests holds the configuration for the resource requests
  requests:
    # cpu defines the cpu request limit for the registry server
    cpu: 500m
    # memory defines the memory request limit for the registry server
    memory:

  # limits holds the configuration for the resource limits
  limits:
    # cpu defines the cpu limit for the registry server
    cpu:
    # memory defines the memory limit for the registry server
    memory: 500Mi

# service holds the configuration for the service
service:
  # type is the type of service to create, allowed values are (ClusterIP | NodePort | LoadBalancer)
  type: ClusterIP
  # nodePort is the port to expose the service on if type is NodePort
  nodePort:

# otlp holds the configuration for the opentelemetry collector
otlp:
  # enabled determines if the opentelemetry collector is enabled
  enabled: false
  # endpoint defines the endpoint of the opentelemetry collector, example "http://otel-collector:4317"
  endpoint: "http://opentelemetry-collector.otel-collector:4317"

# Enables one to override the name of the registry
registryName:

# transactionProcessor holds the configuration for the transaction processor
transactionProcessor:
  # replicas defines the number of transaction processor containers to run
  replicas: 3
  # threads defines the number of parallel threads to run per transaction processor
  threads: 5
  # defines the weight in the consistent hash ring used to determine which transaction processor to send a transaction to.
  weight: 10

# blockFinalizer holds the configuration for the block finalizer
blockFinalizer:
  # interval is the interval at which to run the block finalizer, defaults to 30 seconds allowed values are between 00:00:01 and 01:00:00
  interval: 00:05:00

# rabbitmq defines the rabbitmq configuration for rabbitmq, with rabbitmqOperator
rabbitmq:
  # host defines the host of the rabbitmq server in url format 'localhost'
  host:
    # secretRef:
    #   name:
    #   key:
    # configMapRef:
    #   name:
    #   key:
  # amqpPort defines the port of the rabbitmq server
  amqpPort: 5672
    # secretRef:
    #   name:
    #   key:
    # configMapRef:
    #   name:
    #   key:
  # httpPort defines the api management port of the rabbitmq server
  httpPort: 15672
    # secretRef:
    #   name:
    #   key:
    # configMapRef:
    #   name:
    #   key:
  # username defines the username to use to connect to the rabbitmq server
  username:
    # secretRef:
    #   name:
    #   key:
    # configMapRef:
    #   name:
    #   key:
  # password defines the password to use to connect to the rabbitmq server
  password:
    # secretRef:
    #   name:
    #   key:
    # configMapRef:
    #   name:
    #   key:

# postgresql holds the configuration for the postgresql database, each value is required and can be set directly, via a secretRef, or via a configMapRef
postgresql:
  # host defines the host of the postgresql database
  host:
    # secretRef:
    #   name:
    #   key:
    # configMapRef:
    #   name:
    #   key:
  # port defines the port of the postgresql database
  port: 5432
    # secretRef:
    #   name:
    #   key:
    # configMapRef:
    #   name:
    #   key:
  # database defines the name of the postgresql database
  database:
    # secretRef:
    #   name:
    #   key:
    # configMapRef:
    #   name:
    #   key:
  # username defines the username to use to connect to the postgresql database
  username:
    # secretRef:
    #   name:
    #   key:
    # configMapRef:
    #   name:
    #   key:
  # password defines the password to use to connect to the postgresql database
  password:
    # secretRef:
    #   name:
    #   key:
    # configMapRef:
    #   name:
    #   key:

# verifiers defines where each verifier is located
verifiers:
    # type is the type of verifier, namespace of the protobuf transactions
  - type: project_origin.electricity.v1
    # url is the url to the verifier, the service name of the verifier
    url: http://electricity-v1:5000

# immutableRecord holds the configuration for where and how the log is published.
immutableRecord:
  # type determines where the immutable log is send to, supported values are (log | concordium) if concordium is specified, then it must be configured below.
  type: log

  # concordium holds the configuration to contact and publish data on the network
  concordium:
    # rpcUrl are the url on which the local node is available.
    rpcUrl: http://po-concordium:20000
    # rpcToken is the token used to communicate with the node.
    rpcToken: rpcadmin
    # accountAddress must hold the address from which to use CCD
    accountAddress: ""
    # accountKeySecret is a reference to a kubernetes secret that holds the accountKey
    accountKeySecret:
      # name is the name of the kubernetes secret
      name: ""
      # key is the reference to the value within the secret
      key: ""

# migrationWaiter holds the configuration for the migration waiter
migrationWaiter:
  # image holds the configuration for the image to use for the migration waiter
  image:
    registry: docker.io
    # repository is the repository to pull the image from
    repository: bitnami/kubectl
    # tag is the tag to pull defaults to the chart version
    tag: 1.30.4

# redis holds the configuration for the redis subchart https://charts.bitnami.com/bitnami
redis:
  # enabled specifies if the redis subchart should be enabled or not
  enabled: true

  auth:
    # enabled specifies if the redis subchart should be enabled or not
    enabled: false

# concordium holds the configuration for the concordium node
concordium:
  # enabled specified wether or not to run a local node
  enabled: false

  # network denotes which network the concordium node should run on, allowed values are (mainnet | testnet)
  network: ""

  # collector configures the collector that collects statistics from the node and publishes them to the network dashboard.
  collector:
    # enabled specifies if the collector should run or not.
    enabled: true
    # nodeName contains the name to report to the network dashboard. https://concordium.com/block-explorers/
    nodeName: ""
    # interval describes how often to collect the statistics from the node, in milliseconds
    interval: 5000

  # persistence holds the configuration for the persistent storage of the node
  persistence:
    # enabled specifies if the node should use persistent storage or not.
    enabled: true
    # name is the name of the persistent volume claim
    name: po-concordium-data
    # storageClass is the name of the storage class to use, if not specified the default storage class will be used.
    #storageClass:
    # accessMode is the access mode to use for the persistent volume claim, allowed values are (ReadWriteOnce | ReadWriteMany)
    accessMode: ReadWriteOnce
    # size is the size of the persistent volume claim
    size: 100Gi
