version: '3.8'
services:
  eventstore:
    image: postgres:15.1-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./ProjectOrigin.VerifiableEventStore/Services/EventStore/Postgres/scripts/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local