apiVersion: v2
name: project-origin-stack
description: A helm chart for deploying the Project Origin stack
type: application
version: 0.1.0
appVersion: "0.1.0-alpha.18"

annotations:
  artifacthub.io/changes: |
    - kind: updated
      description: Updated the container to version 0.1.0-alpha.18
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/licence: Apache-2.0
  artifacthub.io/links: |
    - name: Source Code
      url: https://github.com/project-origin/registry
  artifacthub.io/prerelease: "true"
  artifacthub.io/operator: "false"
