{{- define "otlp.config" -}}
- name: Otlp__Enabled
  value: {{ .Values.otlp.enabled | quote }}
{{- if .Values.otlp.enabled }}
- name: Otlp__Endpoint
  value: {{ required "otel.endpoint is required when enabled" .Values.otlp.endpoint | quote }}
{{- end }}
{{- end -}}
