---
{{ if .Values.persistance.cloudNativePG.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.persistance.cloudNativePG.name }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.persistance.cloudNativePG.replicas }}
  storage:
    size: {{ .Values.persistance.cloudNativePG.size }}
  bootstrap:
    initdb:
      database: {{ .Values.persistance.cloudNativePG.database }}
      owner: {{ .Values.persistance.cloudNativePG.owner }}
  monitoring:
    enablePodMonitor: true
{{ end }}
