{{- if .Values.concordium.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: po-concordium
spec:
  type: ClusterIP
  selector:
    app: po-concordium-node
  ports:
    - name: grpc
      protocol: TCP
      port: 20000
      targetPort: 20000
{{- end }}
