apiVersion: v1
kind: Service
metadata:
  name: registry-{{ .Release.Name }}
spec:
  type:  {{ .Values.service.type }}
  selector:
    app: registry-{{ .Release.Name }}
  ports:
    - name: grpc
      protocol: TCP
      port: 80
      targetPort: 80
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
