name: Concordium Integration tests

on: [push]

env:
  compose_folder: src/EnergyOrigin.VerifiableEventStore.Tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start Concordium node
        working-directory: ${{ env.compose_folder }}
        run: docker-compose up -d

      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0"

      - name: Run integration tests
        working-directory: src
        run: dotnet test --filter Category=Concordium

      - name: On error output concordium node logs
        if: ${{ failure() }}
        working-directory: ${{ env.compose_folder }}
        run: docker-compose logs
