name: Concordium Integration tests

on:
  pull_request:
    branches:
      - main

env:
  compose_folder: src/ProjectOrigin.VerifiableEventStore.Tests

jobs:
  test:
    runs-on: [self-hosted, concordium-testnet]
    environment: testnet
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@v3

      - name: Print length of key for debugging
        run: echo "${{ secrets.AccountKey }}" | wc -c

      - name: Run integration tests
        env:
          AccountAddress: ${{ secrets.AccountAddress }}
          AccountKey: ${{ secrets.AccountKey }}
        run: make concordium-tests
