name: Concordium Integration tests

on:
  pull_request:
    branches:
      - main

env:
  compose_folder: src/ProjectOrigin.VerifiableEventStore.Tests

jobs:
  test:
    runs-on: [self-hosted, concordium-testnet]
    environment: testnet
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0"

      - name: Run integration tests
        env:
          AccountAddress: ${{ secrets.AccountAddress }}
          AccountKey: ${{ secrets.AccountKey }}
        run: make concordium-tests
