name: Concordium Integration tests

on: [push]

env:
  compose_folder: src/EnergyOrigin.VerifiableEventStore.Tests

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0"

      - name: Run integration tests
        working-directory: src
        run: dotnet test --filter Category=Concordium
