name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # support v1.2.3
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+' #supports alpha versions v1.2.3-alpha.4

jobs:

  publish-client-nuget:
    name: Publish Client Nuget Package
    runs-on: ubuntu-latest
    env:
      project: src/ProjectOrigin.Electricity.Client

    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Setup .NET Core SDK 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0"

      - name: Install windows cross-compile
        run: |
          rustup target add x86_64-pc-windows-msvc

      - name: Build
        shell: bash
        run: dotnet build --configuration Release ${{ env.project }}

      - name: Pack
        shell: bash
        run: dotnet pack --output build --configuration Release --no-restore -p:Version=${{ env.RELEASE_VERSION }} ${{ env.project }}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: nuget-packages
          path: build/*.nupkg
          retention-days: 1

      - name: Publish
        shell: bash
        run: dotnet nuget push build/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - publish-client-nuget
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: "${{ contains( env.GITHUB_REF, '-alpha.') }}"
          generate_release_notes: true
          files: artifacts/**
