# workflow for releasing helm-chart as OCI images on github every time a tag is created
name: Create Helm Release
on:
  push:
    tags:
      - 'chart-v[0-9]+.[0-9]+.[0-9]+' # support v1.2.3
      - 'chart-v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+' #supports alpha versions v1.2.3-alpha.4

env:
  CHART_FOLDER: this/charts/project-origin-stack/

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: this

      - uses: actions/checkout@v3
        with:
          repository: project-origin/helm-registry
          path: helm-registry
          ssh-key: ${{ secrets.HELM_REGISTRY_TOKEN }}

      - name: Get chart name and version
        id: variables
        run: |
          echo "name=$(yq .name < ${{ env.CHART_FOLDER }}/Chart.yaml)" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/*/chart-v}" >> $GITHUB_OUTPUT

      - name: Package and generate index
        run: |
          helm package ${{ env.CHART_FOLDER }} --version ${{ steps.variables.outputs.version }} --destination helm-releases
          helm repo index helm-releases --merge helm-registry/index.yaml --url https://github.com/project-origin/registry/releases/download/chart-v${{ steps.variables.outputs.version }}/
          cp helm-releases/index.yaml helm-registry/index.yaml

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: "${{ contains( env.GITHUB_REF, '-alpha.') }}"
          generate_release_notes: true
          files: helm-releases/${{ steps.variables.outputs.name }}-${{ steps.variables.outputs.version }}.tgz

      - name: Commit index changes
        run: |
          cd helm-registry
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add index.yaml
          git commit -m "Update index.yaml for ${{ steps.variables.outputs.name }}-${{ steps.variables.outputs.version }}"
          git push
