# workflow for releasing helm-chart on github every time a tag is created
name: Create Helm Release
on:
  push:
    tags:
      - 'chart-v[0-9]+.[0-9]+.[0-9]+' # support v1.2.3
      - 'chart-v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+' #supports rc versions v1.2.3-rc.4

env:
  CHART_FOLDER: charts/project-origin-registry/
  HELM_REGISTRY_REPOSITORY: project-origin/helm-registry

jobs:
  release:
    name: Release helm chart
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: this

      - uses: actions/checkout@v3
        with:
          repository: ${{ env.HELM_REGISTRY_REPOSITORY }}
          path: helm-registry
          ssh-key: ${{ secrets.HELM_REGISTRY_TOKEN }}

      - name: Get chart name and version
        id: variables
        run: |
          echo "name=$(yq .name < this/${{ env.CHART_FOLDER }}/Chart.yaml)" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/*/chart-v}" >> $GITHUB_OUTPUT

      - name: Package and generate index
        run: |
          helm package this/${{ env.CHART_FOLDER }} --version ${{ steps.variables.outputs.version }} --destination helm-releases
          helm repo index helm-releases --merge helm-registry/index.yaml --url https://github.com/${{ github.repository }}/releases/download/chart-v${{ steps.variables.outputs.version }}/
          cp helm-releases/index.yaml helm-registry/index.yaml

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: "${{ contains( env.GITHUB_REF, '-rc.') }}"
          generate_release_notes: true
          files: helm-releases/${{ steps.variables.outputs.name }}-${{ steps.variables.outputs.version }}.tgz

      - name: Commit index changes
        run: |
          cd helm-registry
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add index.yaml
          git commit -m "Update index.yaml for ${{ steps.variables.outputs.name }}-${{ steps.variables.outputs.version }}"
          git push
