name: DocFX output

on:
  pull_request:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2

      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: docfx.json

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: '_site'
          push: true
          message: added docfx outtput
          new_branch: docfx
