name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-devcontainer:
    uses: project-origin/.github/.github/workflows/reusable-verify-devcontainer.yaml@5608f84dfc9f4584953f48f7cb1f200e2487f058

  verify-code:
    uses: project-origin/.github/.github/workflows/reusable-verify-code.yaml@5608f84dfc9f4584953f48f7cb1f200e2487f058

  verify-renovate-config:
    uses: project-origin/.github/.github/workflows/reusable-verify-renovate.yaml@5608f84dfc9f4584953f48f7cb1f200e2487f058

  verify-chart:
    uses: project-origin/.github/.github/workflows/reusable-verify-chart.yaml@5608f84dfc9f4584953f48f7cb1f200e2487f058

  verify-container-build:
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@5608f84dfc9f4584953f48f7cb1f200e2487f058
    with:
      imagename: ghcr.io/project-origin/registry-server
      version: test
      context: .
      dockerfile: ./Registry.Dockerfile
      push: false

  verify-concordium:
    name: Verify Concordium integration
    runs-on: ubuntu-22.04
    environment: testnet
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4

      - name: Run integration tests
        env:
          AccountAddress: ${{ secrets.AccountAddress }}
          AccountKey: ${{ secrets.AccountKey }}
        run: make concordium-tests

#  verify-performance:
#    name: Verify performance
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
#
#      - name: Setup .NET Core SDK from global.json
#        uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4
#
#      - name: Verify performance
#        run: make verify-performance
