name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-code:
    name: Verifies code formatting, builds, and runs unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@v4

      - name: Print info
        run: make info

      - name: Build code
        run: make build

      - name: Run tests
        run: make test

      - name: Verify formatting
        run: make lint

  verify-chart:
    name: Verify chart
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@v4

      - name: Verify chart
        run: make verify-chart

  verify-performance:
    name: Verify performance
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@v4

      - name: Verify performance
        run: make verify-performance

  verify-electricity-server-container-build:
    name: Verify electricity container can be built.
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@main
    with:
      imagename: ghcr.io/project-origin/electricity-server
      version: test
      context: ./src
      dockerfile: ./src/ProjectOrigin.Electricity.Server/Dockerfile
      push: false

  verify-registry-server-container-build:
    name: Verify registry container can be built.
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@main
    with:
      imagename: ghcr.io/project-origin/registry-server
      version: test
      context: ./src
      dockerfile: ./src/ProjectOrigin.Registry.Server/Dockerfile
      push: false

  test-devcontainer:
    name: Verify devcontainer works
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build and run tests on devcontainer
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: make test
