name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-devcontainer:
    uses: project-origin/.github/.github/workflows/reusable-verify-devcontainer.yaml@a6bffbe873f21df444a848bf43264385c74553fc

  verify-code:
    uses: project-origin/.github/.github/workflows/reusable-verify-code.yaml@a6bffbe873f21df444a848bf43264385c74553fc

  verify-renovate-config:
    uses: project-origin/.github/.github/workflows/reusable-verify-renovate.yaml@a6bffbe873f21df444a848bf43264385c74553fc

  verify-chart:
    uses: project-origin/.github/.github/workflows/reusable-verify-chart.yaml@a6bffbe873f21df444a848bf43264385c74553fc

  verify-container-build:
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@a6bffbe873f21df444a848bf43264385c74553fc
    with:
      imagename: ghcr.io/project-origin/registry-server
      version: test
      context: .
      dockerfile: ./Registry.Dockerfile
      push: false

  verify-concordium:
    name: Verify Concordium integration
    runs-on: ubuntu-22.04
    environment: testnet
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4

      - name: Run integration tests
        env:
          AccountAddress: ${{ secrets.AccountAddress }}
          AccountKey: ${{ secrets.AccountKey }}
        run: make concordium-tests

  verify-performance:
    name: Verify performance
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4

      - name: Verify performance
        run: make verify-performance
