name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-code:
    name: Verifies code formatting, builds, and runs unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.203"

      - name: Print info
        run: make info

      - name: Build code
        run: make build

      - name: Run tests
        run: make test

      - name: Verify formatting
        run: make lint

  verify-chart:
    name: Verify chart
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Verify chart
        run: make verify-chart

  verify-docfx-build:
    runs-on: ubuntu-latest
    name: Test docfx build
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.203"

      - name: Build code
        run: make build

      - name: Install docfx
        run: dotnet tool install --global docfx --version 2.70.0

      - name: Build Documentation
        run: docfx build doc/docfx.json

  verify-throughput:
    name: Verify throughput
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Verify throughput
        run: make verify-throughput
