name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-devcontainer:
    uses: project-origin/.github/.github/workflows/reusable-verify-devcontainer.yaml@b871f6795bf0d71b8b9bb61ee6bf7699f0960375

  verify-code:
    uses: project-origin/.github/.github/workflows/reusable-verify-code.yaml@b871f6795bf0d71b8b9bb61ee6bf7699f0960375

  verify-renovate-config:
    uses: project-origin/.github/.github/workflows/reusable-verify-renovate.yaml@b871f6795bf0d71b8b9bb61ee6bf7699f0960375

  verify-chart:
    uses: project-origin/.github/.github/workflows/reusable-verify-chart.yaml@b871f6795bf0d71b8b9bb61ee6bf7699f0960375

  verify-container-build:
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@b871f6795bf0d71b8b9bb61ee6bf7699f0960375
    with:
      imagename: ghcr.io/project-origin/registry-server
      version: test
      context: .
      dockerfile: ./Registry.Dockerfile
      push: false

  verify-concordium:
    name: Verify Concordium integration
    runs-on: ubuntu-22.04
    environment: testnet
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4

      - name: Run integration tests
        env:
          AccountAddress: ${{ secrets.AccountAddress }}
          AccountKey: ${{ secrets.AccountKey }}
        run: make concordium-tests

  verify-performance:
    name: Verify performance
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4

      - name: Verify performance
        run: make verify-performance
