name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-devcontainer:
    uses: project-origin/.github/.github/workflows/reusable-verify-devcontainer.yaml@c3636dc0f4074360ec7c43680243c39cc6894565

  verify-code:
    uses: project-origin/.github/.github/workflows/reusable-verify-code.yaml@c3636dc0f4074360ec7c43680243c39cc6894565

  verify-renovate-config:
    uses: project-origin/.github/.github/workflows/reusable-verify-renovate.yaml@c3636dc0f4074360ec7c43680243c39cc6894565

  verify-chart:
    uses: project-origin/.github/.github/workflows/reusable-verify-chart.yaml@c3636dc0f4074360ec7c43680243c39cc6894565

  verify-container-build:
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@c3636dc0f4074360ec7c43680243c39cc6894565
    with:
      imagename: ghcr.io/project-origin/registry-server
      version: test
      context: ./src
      dockerfile: ./src/ProjectOrigin.Registry.Server/Dockerfile
      push: false

  verify-concordium:
    name: Verify Concordium integration
    runs-on: [self-hosted, concordium-testnet]
    environment: testnet
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4

      - name: Run integration tests
        env:
          AccountAddress: ${{ secrets.AccountAddress }}
          AccountKey: ${{ secrets.AccountKey }}
        run: make concordium-tests

  verify-performance:
    name: Verify performance
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4

      - name: Verify performance
        run: make verify-performance
