name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-devcontainer:
    uses: project-origin/.github/.github/workflows/reusable-verify-devcontainer.yaml@f1b70f57e551b400e053f68b56dc5e63d2e7eb42

  verify-code:
    uses: project-origin/.github/.github/workflows/reusable-verify-code.yaml@f1b70f57e551b400e053f68b56dc5e63d2e7eb42

  verify-renovate-config:
    uses: project-origin/.github/.github/workflows/reusable-verify-renovate.yaml@f1b70f57e551b400e053f68b56dc5e63d2e7eb42

  verify-chart:
    uses: project-origin/.github/.github/workflows/reusable-verify-chart.yaml@f1b70f57e551b400e053f68b56dc5e63d2e7eb42

  verify-container-build:
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@f1b70f57e551b400e053f68b56dc5e63d2e7eb42
    with:
      imagename: ghcr.io/project-origin/registry-server
      version: test
      context: .
      dockerfile: ./Registry.Dockerfile
      push: false

  verify-concordium:
    name: Verify Concordium integration
    runs-on: ubuntu-24.04
    environment: testnet
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4

      - name: Run integration tests
        env:
          AccountAddress: ${{ secrets.AccountAddress }}
          AccountKey: ${{ secrets.AccountKey }}
        run: make concordium-tests

#  verify-performance:
#    name: Verify performance
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
#
#      - name: Setup .NET Core SDK from global.json
#        uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4
#
#      - name: Verify performance
#        run: make verify-performance
