name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-devcontainer:
    uses: project-origin/.github/.github/workflows/reusable-verify-devcontainer.yaml@53ea6c13d75195b9a3f782d299fe45201af66522

  verify-code:
    uses: project-origin/.github/.github/workflows/reusable-verify-code.yaml@53ea6c13d75195b9a3f782d299fe45201af66522

  verify-renovate-config:
    uses: project-origin/.github/.github/workflows/reusable-verify-renovate.yaml@53ea6c13d75195b9a3f782d299fe45201af66522

  verify-chart:
    uses: project-origin/.github/.github/workflows/reusable-verify-chart.yaml@53ea6c13d75195b9a3f782d299fe45201af66522

  verify-container-build:
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@53ea6c13d75195b9a3f782d299fe45201af66522
    with:
      imagename: ghcr.io/project-origin/registry-server
      version: test
      context: .
      dockerfile: ./Registry.Dockerfile
      push: false

  verify-concordium:
    name: Verify Concordium integration
    runs-on: ubuntu-24.04
    environment: testnet
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5

      - name: Run integration tests
        env:
          AccountAddress: ${{ secrets.AccountAddress }}
          AccountKey: ${{ secrets.AccountKey }}
        run: make concordium-tests

#  verify-performance:
#    name: Verify performance
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
#
#      - name: Setup .NET Core SDK from global.json
#        uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4
#
#      - name: Verify performance
#        run: make verify-performance
