name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-devcontainer:
    uses: project-origin/.github/.github/workflows/reusable-verify-devcontainer.yaml@70d922e7416caf49b8f2a1f54cfeb0e1d738da2b

  verify-code:
    uses: project-origin/.github/.github/workflows/reusable-verify-code.yaml@70d922e7416caf49b8f2a1f54cfeb0e1d738da2b

  verify-renovate-config:
    uses: project-origin/.github/.github/workflows/reusable-verify-renovate.yaml@70d922e7416caf49b8f2a1f54cfeb0e1d738da2b

  verify-chart:
    uses: project-origin/.github/.github/workflows/reusable-verify-chart.yaml@70d922e7416caf49b8f2a1f54cfeb0e1d738da2b

  verify-container-build:
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@70d922e7416caf49b8f2a1f54cfeb0e1d738da2b
    with:
      imagename: ghcr.io/project-origin/registry-server
      version: test
      context: ./src
      dockerfile: ./src/ProjectOrigin.Registry.Server/Dockerfile
      push: false

  verify-concordium:
    name: Verify Concordium integration
    runs-on: [self-hosted, concordium-testnet]
    environment: testnet
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4

      - name: Run integration tests
        env:
          AccountAddress: ${{ secrets.AccountAddress }}
          AccountKey: ${{ secrets.AccountKey }}
        run: make concordium-tests

  verify-performance:
    name: Verify performance
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4

      - name: Verify performance
        run: make verify-performance
