name: Build release artifacts

on:
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  define-version:
    uses: project-origin/.github/.github/workflows/reusable-tag-version.yaml@e346a7e85cac25b0b08ccdb1ff4af3860be70846

  publish-container:
    needs:
      - define-version
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@e346a7e85cac25b0b08ccdb1ff4af3860be70846
    with:
      imagename: ghcr.io/project-origin/registry-server
      version: ${{ needs.define-version.outputs.version }}
      context: .
      dockerfile: ./Registry.Dockerfile
      push: true

  publish-chart:
    needs:
      - define-version
      - publish-container
    uses: project-origin/.github/.github/workflows/reusable-publish-chart.yaml@e346a7e85cac25b0b08ccdb1ff4af3860be70846
    with:
      version: ${{ needs.define-version.outputs.version }}
      chart_folder: chart
      helm_registry_repository: project-origin/helm-registry
      prerelease: ${{ github.event.release.prerelease }}
    secrets:
      helm_registry_token: ${{ secrets.HELM_REGISTRY_TOKEN }}
