name: Build release artifacts

on:
  release:
    types: [published]

jobs:
  define-version:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.output-version.outputs.version }}

    steps:
      - uses: actions/checkout@v3

      - name: Set env
        id: output-version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

  publish-hdkeys-nuget:
    name: Publish Hierarchical Deterministic Keys Nuget package
    needs:
      - define-version
    runs-on: ubuntu-20.04
    env:
      project: src/ProjectOrigin.HierarchicalDeterministicKeys

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.203"

      - name: Build
        shell: bash
        run: dotnet build --configuration Release ${{ env.project }}

      - name: Pack
        shell: bash
        run: dotnet pack --output build --configuration Release --no-restore -p:Version=${{ needs.define-version.outputs.version }} ${{ env.project }}

      - uses: actions/upload-artifact@v3
        with:
          path: build/*.nupkg

      - name: Publish
        shell: bash
        run: dotnet nuget push build/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

  publish-electricity-server-container:
    needs:
      - define-version
    uses: project-origin/.github/.github/workflows/reusable-build-container.yaml@main
    with:
      imagename: ghcr.io/project-origin/electricity-server
      version: ${{ needs.define-version.outputs.version }}
      context: ./src
      dockerfile: ./src/ProjectOrigin.Electricity.Server/Dockerfile
    secrets:
      pushtoken: ${{ github.token }}

  publish-registry-server-container:
    needs:
      - define-version
    uses: project-origin/.github/.github/workflows/reusable-build-container.yaml@main
    with:
      imagename: ghcr.io/project-origin/registry-server
      version: ${{ needs.define-version.outputs.version }}
      context: ./src
      dockerfile: ./src/ProjectOrigin.Registry.Server/Dockerfile
    secrets:
      pushtoken: ${{ github.token }}

  publish-chart:
    name: Publish helm chart
    runs-on: ubuntu-22.04
    needs:
      - define-version
    env:
      CHART_FOLDER: charts/project-origin-registry
      HELM_REGISTRY_REPOSITORY: project-origin/helm-registry

    steps:
      - uses: actions/checkout@v3
        with:
          path: this

      - uses: actions/checkout@v3
        with:
          repository: ${{ env.HELM_REGISTRY_REPOSITORY }}
          path: helm-registry
          ssh-key: ${{ secrets.HELM_REGISTRY_TOKEN }}

      - name: Get chart name
        id: variables
        run: |
          echo "name=$(yq .name < this/${{ env.CHART_FOLDER }}/Chart.yaml)" >> $GITHUB_OUTPUT

      - name: Package and generate index
        run: |
          helm package this/${{ env.CHART_FOLDER }} --version ${{ needs.define-version.outputs.version }} --app-version "${{ needs.define-version.outputs.version }}" --destination helm-releases
          helm repo index helm-releases --merge helm-registry/index.yaml --url https://github.com/${{ github.repository }}/releases/download/v${{ needs.define-version.outputs.version }}/
          cp helm-releases/index.yaml helm-registry/index.yaml

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: "${{ contains( env.GITHUB_REF, '-rc.') }}"
          generate_release_notes: true
          files: helm-releases/${{ steps.variables.outputs.name }}-${{ needs.define-version.outputs.version }}.tgz

      - uses: actions/upload-artifact@v3
        with:
          path: helm-releases/${{ steps.variables.outputs.name }}-${{ needs.define-version.outputs.version }}.tgz

      - name: Commit index changes
        run: |
          cd helm-registry
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add index.yaml
          git commit -m "Update index.yaml for ${{ steps.variables.outputs.name }}-${{ needs.define-version.outputs.version }}"
          git push
