name: Build release artifacts

on:
  release:
    types: [published]

jobs:
  define-version:
    uses: project-origin/.github/.github/workflows/reusable-tag-version.yaml@32ff33baaf1c9960ef1f01ef4ee554225db1972c

  publish-container:
    needs:
      - define-version
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@32ff33baaf1c9960ef1f01ef4ee554225db1972c
    with:
      imagename: ghcr.io/project-origin/registry-server
      version: ${{ needs.define-version.outputs.version }}
      context: .
      dockerfile: ./Registry.Dockerfile
      push: true

  publish-chart:
    needs:
      - define-version
      - publish-container
    uses: project-origin/.github/.github/workflows/reusable-publish-chart.yaml@32ff33baaf1c9960ef1f01ef4ee554225db1972c
    with:
      version: ${{ needs.define-version.outputs.version }}
      chart_folder: charts/project-origin-registry
      helm_registry_repository: project-origin/helm-registry
    secrets:
      helm_registry_token: ${{ secrets.HELM_REGISTRY_TOKEN }}
