name: Build release artifacts

on:
  release:
    types: [published]

jobs:
  define-version:
    uses: project-origin/.github/.github/workflows/reusable-tag-version.yaml@639a49296c45ee5e9859b6cd7356a380025d9959

  publish-container:
    needs:
      - define-version
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@639a49296c45ee5e9859b6cd7356a380025d9959
    with:
      imagename: ghcr.io/project-origin/registry-server
      version: ${{ needs.define-version.outputs.version }}
      context: ./src
      dockerfile: ./src/ProjectOrigin.Registry.Server/Dockerfile
      push: true

  publish-chart:
    needs:
      - define-version
      - publish-container
    uses: project-origin/.github/.github/workflows/reusable-publish-chart.yaml@639a49296c45ee5e9859b6cd7356a380025d9959
    with:
      version: ${{ needs.define-version.outputs.version }}
      chart_folder: charts/project-origin-registry
      helm_registry_repository: project-origin/helm-registry
    secrets:
      helm_registry_token: ${{ secrets.HELM_REGISTRY_TOKEN }}
