name: Build release artifacts

on:
  release:
    types: [published]

jobs:
  define-version:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.output-version.outputs.version }}

    steps:
      - uses: actions/checkout@v3

      - name: Set env
        id: output-version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

  publish-electricity-server-container:
    needs:
      - define-version
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@main
    with:
      imagename: ghcr.io/project-origin/electricity-server
      version: ${{ needs.define-version.outputs.version }}
      context: ./src
      dockerfile: ./src/ProjectOrigin.Electricity.Server/Dockerfile
      push: true

  publish-registry-server-container:
    needs:
      - define-version
    uses: project-origin/.github/.github/workflows/reusable-build-push-container-ghcr.yaml@main
    with:
      imagename: ghcr.io/project-origin/registry-server
      version: ${{ needs.define-version.outputs.version }}
      context: ./src
      dockerfile: ./src/ProjectOrigin.Registry.Server/Dockerfile
      push: true

  publish-chart:
    name: Publish helm chart
    runs-on: ubuntu-22.04
    needs:
      - define-version
    env:
      CHART_FOLDER: charts/project-origin-registry
      HELM_REGISTRY_REPOSITORY: project-origin/helm-registry

    steps:
      - uses: actions/checkout@v3
        with:
          path: this

      - uses: actions/checkout@v3
        with:
          repository: ${{ env.HELM_REGISTRY_REPOSITORY }}
          path: helm-registry
          ssh-key: ${{ secrets.HELM_REGISTRY_TOKEN }}

      - name: Get chart name
        id: variables
        run: |
          echo "name=$(yq .name < this/${{ env.CHART_FOLDER }}/Chart.yaml)" >> $GITHUB_OUTPUT

      - name: Package and generate index
        run: |
          helm repo add bitnami-charts https://charts.bitnami.com/bitnami
          helm dependency build this/${{ env.CHART_FOLDER }}
          helm package this/${{ env.CHART_FOLDER }} --version ${{ needs.define-version.outputs.version }} --app-version "${{ needs.define-version.outputs.version }}" --destination helm-releases
          helm repo index helm-releases --merge helm-registry/index.yaml --url https://github.com/${{ github.repository }}/releases/download/v${{ needs.define-version.outputs.version }}/
          cp helm-releases/index.yaml helm-registry/index.yaml

      - uses: actions/upload-artifact@v3
        with:
          path: helm-releases/${{ steps.variables.outputs.name }}-${{ needs.define-version.outputs.version }}.tgz

      - name: Commit index changes
        run: |
          cd helm-registry
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add index.yaml
          git commit -m "Update index.yaml for ${{ steps.variables.outputs.name }}-${{ needs.define-version.outputs.version }}"
          git push
