name: Renovate

on:
  schedule:
    - cron: 0 10 * * *
  push:
    branches:
      - renovate-config/**

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: tibdex/github-app-token@v2
        id: get_installation_token
        with:
          app_id: ${{ vars.RENOVATE_GH_APP_ID }}
          private_key: ${{ secrets.RENOVATE_GH_APP_PRIVATE_KEY }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.4
        with:
          configurationFile: .github/renovate-config.json
          token: ${{ steps.get_installation_token.outputs.token }}

