name: Renovate

on:
  schedule:
    - cron: 0 * * * *

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          configurationFile: .github/renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
