name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyse:
    uses: project-origin/.github/.github/workflows/reusable-sonarcloud.yaml@5af97766177af15e9b84338f6327bc50705a1c61
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
