name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyse:
    uses: project-origin/.github/.github/workflows/reusable-sonarcloud.yaml@8b73fb4eb0fd5b44058e41f2de0edff0d8ce2a41
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
