name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: sonar-analysis
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@v4

      - name: Restore
        shell: bash
        run: |
          make restore

      - name: Install dotnet-sonarscanner
        shell: bash
        run: |
          dotnet tool install --global dotnet-sonarscanner

      - name: Install dotnet-coverage
        shell: bash
        run: |
          dotnet tool install --global dotnet-coverage

      - name: Run Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: bash
        run: |
          dotnet sonarscanner begin -k:"${{ vars.SONAR_PROJECTKEY }}" -o:"${{ vars.SONAR_ORGANIZATION }}" -d:sonar.token="${{ secrets.SONAR_TOKEN }}" -d:sonar.host.url="https://sonarcloud.io" -d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet build --no-incremental src
          dotnet-coverage collect 'make test' -f xml -o "coverage.xml"
          dotnet sonarscanner end -d:sonar.token="${{ secrets.SONAR_TOKEN }}"
