name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyse:
    uses: project-origin/.github/.github/workflows/reusable-sonarcloud.yaml@1a78d52ab07ce81a1c36a32988eae023e6e32199
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
