name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyse:
    uses: project-origin/.github/.github/workflows/reusable-sonarcloud.yaml@7a3afc06579e2b30d0f0b1511a16ac2209a696a2
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
